### ISSUE TITLE
Mount SD failed

### ISSUE THREAD

**Issue by CecilFF4** [ihaveamac/fuse-3ds#2]
Tried mounting a `Nintendo 3DS` folder through the "SD Card Contents" option. Mounts fine using the non-gui version but freezes the gui version. Hangs when attempting to mount to a drive letter. Left it alone for many minutes and it just stayed frozen until I ctrl-c the console. Output is below. When attempting to mount to a directory, however, it says "[folder] is not accessible. Incorrect function.", with no errors or tracebacks in the console.

Running: ['D:\\Games\\Nintendo\\3DS\\Hack\\PC\\Fuse-3DS\\fuse-3ds-1.0b1-x64.exe', 'sd', '-f', 'D:/Games/Nintendo/3DS/SD/_Jon/Nintendo 3DS', 'A:', '--movable', 'D:/Games/Nintendo/3DS/Hack/PC/Fuse-3DS/movable.sed', '-r']
fuse-3ds 1.0b1 - https://github.com/ihaveamac/fuse-3ds
Root dir: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Key:      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
The service fuse-3ds-1.0b1-x64 has been started.
Exception in Tkinter callback
Traceback (most recent call last):
  File "Z:\ThingsMore\nintendo\3DS\fuse-3ds\fuse3ds\_gui.py", line 171, in press
  File "Z:\ThingsMore\nintendo\3DS\fuse-3ds\fuse3ds\_gui.py", line 106, in run_mount
  File "C:\Users\Ian Burgwin\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 1057, in wait
subprocess.TimeoutExpired: Command '['D:\\Games\\Nintendo\\3DS\\Hack\\PC\\Fuse-3DS\\fuse-3ds-1.0b1-x64.exe', 'sd', '-f', 'D:/Games/Nintendo/3DS/SD/_Jon/Nintendo 3DS', 'A:', '--movable', 'D:/Games/Nintendo/3DS/Hack/PC/Fuse-3DS/movable.sed', '-r']' timed out after 3 seconds

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Ian Burgwin\AppData\Local\Programs\Python\Python36\lib\tkinter\__init__.py", line 1699, in __call__
  File "C:\Users\Ian Burgwin\AppData\Local\Programs\Python\Python36\lib\site-packages\appJar\appjar.py", line 3494, in <lambda>
  File "Z:\ThingsMore\nintendo\3DS\fuse-3ds\fuse3ds\_gui.py", line 177, in press
KeyboardInterrupt

**Comment by ihaveamac** [comment]
"fuse-3ds-1.0b1-x64.exe" you should probably try the latest release. I just put [v1.0b4.dev1](https://github.com/ihaveamac/fuse-3ds/releases/tag/v1.0b4.dev1) to quickly fix an issue that broke the SD mount on Windows.

**Comment by CecilFF4** [comment]
Same error with the drive letter and same error with the directory. Drive letter console output is nearly identical to the previous comment.

Running: ['D:\\Games\\Nintendo\\3DS\\Hack\\PC\\Fuse-3DS\\fuse-3ds-1.0b4.dev1-x64.exe', 'sd', '-f', 'D:/Games/Nintendo/3DS/SD/_Jon/Nintendo 3DS', 'Z:', '--movable', 'D:/Games/Nintendo/3DS/Hack/PC/Fuse-3DS/movable.sed', '-r']
fuse-3ds 1.0b4.dev1 - https://github.com/ihaveamac/fuse-3ds
Root dir: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Key:      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
The service fuse-3ds-1.0b4.dev1 has been started.
Exception in Tkinter callback
Traceback (most recent call last):
  File "Z:\ThingsMore\nintendo\3DS\fuse-3ds\fuse3ds\_gui.py", line 181, in press
  File "Z:\ThingsMore\nintendo\3DS\fuse-3ds\fuse3ds\_gui.py", line 109, in run_mount
  File "C:\Users\Ian Burgwin\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 1057, in wait
subprocess.TimeoutExpired: Command '['D:\\Games\\Nintendo\\3DS\\Hack\\PC\\Fuse-3DS\\fuse-3ds-1.0b4.dev1-x64.exe', 'sd', '-f', 'D:/Games/Nintendo/3DS/SD/_Jon/Nintendo 3DS', 'Z:', '--movable', 'D:/Games/Nintendo/3DS/Hack/PC/Fuse-3DS/movable.sed', '-r']' timed out after 3 seconds

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Ian Burgwin\AppData\Local\Programs\Python\Python36\lib\tkinter\__init__.py", line 1702, in __call__
  File "C:\Users\Ian Burgwin\AppData\Local\Programs\Python\Python36\lib\site-packages\appJar\appjar.py", line 3494, in <lambda>
  File "Z:\ThingsMore\nintendo\3DS\fuse-3ds\fuse3ds\_gui.py", line 187, in press
KeyboardInterrupt

**Comment by ihaveamac** [comment]
it seems this may be failing:
https://github.com/ihaveamac/fuse-3ds/blob/d31acf3418b2bbf5bcb9b918a6ffe92d5339d126/fuse3ds/_gui.py#L182-L193
not sure why the check would be failing, putting it into an endless sleep loop. maybe try rebooting, or choosing a directory mount?
